admin:
  path: /admin/
  methods: [GET]
  controller: OpenCFP\Http\Action\Admin\DashboardAction

admin_talks:
  path: /admin/talks
  methods: [GET]
  controller: OpenCFP\Http\Action\Admin\Talk\IndexAction

admin_talk_view:
  path: '/admin/talks/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Admin\Talk\ViewAction

admin_talk_favorite:
  path: '/admin/talks/{id}/favorite'
  methods: [POST]
  controller: 'OpenCFP\Http\Controller\Admin\TalksController::favoriteAction'

admin_talk_select:
  path: '/admin/talks/{id}/select'
  methods: [POST]
  controller: 'OpenCFP\Http\Controller\Admin\TalksController::selectAction'

admin_talk_comment_create:
  path: '/admin/talks/{id}/comment'
  methods: [POST]
  controller: 'OpenCFP\Http\Controller\Admin\TalksController::commentCreateAction'

admin_talk_rate:
  path: '/admin/talks/{id}/rate'
  methods: [POST]
  controller: OpenCFP\Http\Action\Admin\Talk\RateAction

admin_speakers:
  path: /admin/speakers
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\SpeakersController::indexAction'

admin_speaker_view:
  path: '/admin/speakers/{id}'
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\SpeakersController::viewAction'

admin_speaker_promote:
  path: '/admin/speakers/{id}/promote'
  methods: [GET]
  controller: OpenCFP\Http\Action\Admin\Speaker\PromoteAction
  defaults: { _require_csrf_token: true }

admin_speaker_demote:
  path: '/admin/speakers/{id}/demote'
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\SpeakersController::demoteAction'
  defaults: { _require_csrf_token: true }

admin_speaker_delete:
  path: '/admin/speakers/delete/{id}'
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\SpeakersController::deleteAction'
  defaults: { _require_csrf_token: true }

admin_export_csv:
  path: /admin/export/csv
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\ExportsController::attributedTalksExportAction'

admin_export_csv_anon:
  path: /admin/export/csv/anon
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\ExportsController::anonymousTalksExportAction'

admin_export_csv_selected:
  path: /admin/export/csv/selected
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\ExportsController::selectedTalksExportAction'

admin_export_csv_emails:
  path: /admin/export/csv/emails
  methods: [GET]
  controller: 'OpenCFP\Http\Controller\Admin\ExportsController::emailExportAction'

reviewer:
  path: /reviewer/
  methods: [GET]
  controller: OpenCFP\Http\Action\Reviewer\DashboardAction

reviewer_talks:
  path: /reviewer/talks
  methods: [GET]
  controller: OpenCFP\Http\Action\Reviewer\Talk\IndexAction

reviewer_talk_view:
  path: '/reviewer/talks/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Reviewer\Talk\ViewAction

reviewer_talk_rate:
  path: '/reviewer/talks/{id}/rate'
  methods: [POST]
  controller: OpenCFP\Http\Action\Reviewer\Talk\RateAction

reviewer_speaker_view:
  path: '/reviewer/speakers/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Reviewer\Speaker\ViewAction

homepage:
  path: /
  methods: [GET]
  controller: OpenCFP\Http\Action\Page\HomePageAction

speaker_package:
  path: /package
  methods: [GET]
  controller: FrameworkBundle:Template:template
  defaults:
    template: package.twig

talk_ideas:
  path: /ideas
  methods: [GET]
  controller: FrameworkBundle:Template:template
  defaults:
    template: ideas.twig

dashboard:
  path: /dashboard
  methods: [GET]
  controller: OpenCFP\Http\Action\DashboardAction

talk_edit:
  path: '/talk/edit/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Talk\EditAction
  defaults: { _require_csrf_token: true }

talk_new:
  path: /talk/create
  methods: [GET]
  controller: OpenCFP\Http\Action\Talk\CreateAction

talk_create:
  path: /talk/create
  methods: [POST]
  controller: OpenCFP\Http\Action\Talk\CreateProcessAction
  defaults: { _require_csrf_token: true }

talk_update:
  path: /talk/update
  methods: [POST]
  controller: OpenCFP\Http\Action\Talk\UpdateAction
  defaults: { _require_csrf_token: true }

talk_delete:
  path: /talk/delete
  methods: [POST]
  controller: OpenCFP\Http\Action\Talk\DeleteAction
  defaults: { _require_csrf_token: true }

talk_view:
  path: '/talk/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Talk\ViewAction

login:
  path: /login
  methods: [GET]
  controller: OpenCFP\Http\Action\Security\ShowLogInAction

login_check:
  path: /login
  methods: [POST]
  controller: OpenCFP\Http\Action\Security\LogInAction

logout:
  path: /logout
  methods: [GET]
  controller: OpenCFP\Http\Action\Security\LogOutAction

user_new:
  path: /signup
  methods: [GET]
  controller: OpenCFP\Http\Action\Signup\IndexAction

user_create:
  path: /signup
  methods: [POST]
  controller: OpenCFP\Http\Action\Signup\ProcessAction

user_edit:
  path: '/profile/edit/{id}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Profile\EditAction

user_update:
  path: /profile/edit
  methods: [POST]
  controller: OpenCFP\Http\Action\Profile\ProcessAction

user_delete:
  path: /profile/delete
  methods: [GET]
  controller: OpenCFP\Http\Action\Profile\DeleteAction

user_delete_process:
  path: /profile/delete
  methods: [POST]
  controller: OpenCFP\Http\Action\Profile\ProcessDeleteAction

password_edit:
  path: /profile/change_password
  methods: [GET]
  controller: FrameworkBundle:Template:template
  defaults:
    template: user/change_password.twig

password_change:
  path: /profile/change_password
  methods: [POST]
  controller: OpenCFP\Http\Action\Profile\ChangePasswordProcessAction

forgot_password:
  path: /forgot
  methods: [GET]
  controller: OpenCFP\Http\Action\Forgot\IndexAction

forgot_password_create:
  path: /forgot
  methods: [POST]
  controller: 'OpenCFP\Http\Controller\ForgotController::sendResetAction'

reset_password_create:
  path: /reset
  methods: [POST]
  controller: 'OpenCFP\Http\Controller\ForgotController::resetAction'

reset_password:
  path: '/reset/{user_id}/{reset_code}'
  methods: [GET]
  controller: OpenCFP\Http\Action\Forgot\ResetProcessAction

password_update:
  path: /updatepassword
  methods: [POST]
  controller: OpenCFP\Http\Action\Forgot\UpdatePasswordAction

privacy:
   path: /privacy
   methods: [GET]
   controller: OpenCFP\Http\Action\Signup\PrivacyAction

sso:
  path: /sso
  methods: [GET]
  controller: OpenCFP\Http\Action\Security\SsoAction

sso_redirect:
  path: /sso/redirect
  methods: [GET]
  controller: OpenCFP\Http\Action\Security\SsoRedirectAction
