language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WITH_COVERAGE=true
    - php: 5.6
      env: WITH_CS=true

env:
  global:
    - TRAVIS_DB=cfp_test
    - CODECLIMATE_REPO_TOKEN=9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

# cache composer downloads so installing is quicker
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then COLLECT_COVERAGE=true; else COLLECT_COVERAGE=false; fi
  - if [[ "$COLLECT_COVERAGE" == "false" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate --no-check-publish

install:
  - composer install

before_script:
  - sh tools/travis/setup-mail.sh
  - mysql -e "CREATE DATABASE $TRAVIS_DB" -uroot
  - cp phinx.yml.dist phinx.yml
  - vendor/bin/phinx migrate -e testing

script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --verbose --diff; fi

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report build/logs/clover.xml; fi
