language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WITH_CS=true
    - php: 7.1
      env: WITH_COVERAGE=true

env:
  global:
    - TRAVIS_DB=cfp_test
    - CC_TEST_REPORTER_ID=9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test
  - asset

jobs:
  include:
    - stage: Style

      php: 7.0

      before_install:
        - phpenv config-rm xdebug.ini
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - mkdir -p "$HOME/.php-cs-fixer"

      script:
        - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose

    - stage: Test

      php: 7.0

      addons:
        apt:
          sources:
            - travis-ci/sqlite3
          packages:
            - sqlite3

      before_install:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then WITH_COVERAGE=true; else WITH_COVERAGE=false; fi
        - if [[ "$WITH_COVERAGE" == "false" ]]; then phpenv config-rm xdebug.ini; fi
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - sh tools/travis/setup-mail.sh
        - mysql -e "CREATE DATABASE $TRAVIS_DB" -uroot
        - cp phinx.yml.dist phinx.yml
        - vendor/bin/phinx migrate -e testing
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build

      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

      script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report build/logs/clover.xml; fi

    - stage: Asset

      php: 7.0

      before_install:
        - nvm install 8.8.1

      install:
        - yarn install

      script:
        - yarn run production
